CLEAN_TICKERS="A AAL AAP AAPL ABBV ADI ADM ADP ADS AEE AEP AES AET AFL AGN AIV AIZ AJG ALB ALK ALL ALLE ALXN AME AMG AMGN AMP AMT AMZN AN ANTM AON APA APC APD APH ATVI AVB AVGO AVY AWK AXP AYI AZO BA BAC BAX BBBY BBT BCR BDX BEN BHI BIIB BLK BLL BMY BXP C CA CAG CAH CAT CB CBG CBS CCI CCL CF CFG CI CL CLX CMA CMG CMI CMS CNC COF COG COH COP CPB CRM CSCO CSRA CSX CTAS CTSH CVS CVX CXO D DD DE DFS DG DGX DHI DHR DIS DISCK DLPH DLR DLTR DNB DO DOV DOW DPS DRI DTE DUK DVA DVN EA ECL ED EFX EIX EL EMN EMR ENDP EOG EQIX EQR EQT ESS ETN ETR EW EXR F FAST FB FBHS FCX FDX FE FFIV FIS FISV FITB FL FLR FLS FMC FOX FRT FSLR FTI FTV GD GE GIS GLW GPC GPN GPS GS GT GWW HAL HAS HBAN HBI HCN HCP HD HES HOG HON HP HPE HRB HRL HRS HSIC HST HSY HUM IBM IFF ILMN INTU IP IR IRM ITW IVZ JBHT JCI JNJ JNPR JPM JWN K KIM KMB KMI KMX KO KORS KR KSS KSU L LEG LEN LH LKQ LL LLL LLY LM LMT LNT LOW LRCX LUK LUV LYB M MA MAC MAR MAS MAT MCD MCK MCO MDLZ MDT MET MHK MJN MKC MLM MMC MMM MNK MO MON MOS MPC MRK MRO MTB MU MUR NBL NEE NEM NFLX NFX NKE NLSN NOC NOV NRG NSC NTAP NUE NWL O OI OKE OMC ORCL ORLY OXY PAYX PBI PCAR PCG PCLN PDCO PEG PEP PFE PFG PG PGR PH PKI PNC PNR PNW PPL PRGO PRU PSA PSX PVH PWR PX PXD PYPL QRVO RAI RCL REGN RF RHI RHT RIG RL ROK ROP RRC RSG RTN SCG SCHW SEE SHW SJM SLB SLG SNA SNI SO SPG SPGI SPLS SPY SRCL SRE STI STX STZ SWK SWKS SWN SYF SYK SYMC SYY T TAP TDC TDG TEL TGNA TGT TIF TJX TROW TRV TSCO TSN TSO TSS TWX TXN TXT UDR UHS UNH UNM UNP UPS URI USB UTX V VAR VFC VIAB VLO VMC VNO VRSK VRSN VRTX VTR VZ WAT WBA WDC WEC WFC WHR WLTW WM WMB WMT WRK WU WY WYN WYNN XEC XEL XLNX XOM XRAY XRX XYL YHOO YUM ZBH ZTS"

ARGS=$@

if [ -z "$1" ]
  then
    echo "using clean S&P500 tickers..."
    ARGS=$CLEAN_TICKERS
fi

make
python tradier-sqlite.py -v $ARGS
./airis opt $ARGS
./airis sig $ARGS
./airis sim
